version: "3"

services:
  db:
    image: adrienpessu/docker-maven-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
